version: "3.9"

name: pegtimeldeers

networks:
  t2_proxy:
    name: t2_proxy
    external: true

services:
  main:
    build:
      context: "./app"
      dockerfile: Dockerfile
    networks:
      - t2_proxy
    restart: unless-stopped    
    labels:
      traefik.enable: true
      traefik.http.routers.hse-pegtimeldeers-rtr.entrypoints: http
      traefik.http.routers.hse-pegtimeldeers-rtr.rule: Host(`pegtimeldeers.linghub.net`)
      traefik.http.routers.hse-pegtimeldeers-rtr.service: hse-pegtimeldeers-svc
      traefik.http.services.hse-pegtimeldeers-svc.loadbalancer.server.port: 80
      org.label-schema.group: "monitoring"

  pixplot:
    build:
      context: "./pixplot"
      dockerfile: Dockerfile
    restart: unless-stopped      
    networks:
      - t2_proxy
    labels:
      traefik.enable: true
      traefik.http.routers.hse-pixplot-rtr.entrypoints: http
      traefik.http.routers.hse-pixplot-rtr.rule: Host(`pegtimeldeers.linghub.net`) && PathPrefix(`/pixplot`)
      traefik.http.routers.hse-pixplot-rtr.service: hse-pixplot-svc
      traefik.http.services.hse-pixplot-svc.loadbalancer.server.port: 80
      org.label-schema.group: "monitoring"